FROM ubuntu:24.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 systemd systemd-sysv dbus && rm -rf /var/lib/apt/lists/*
WORKDIR /review
ENV container=docker
CMD ["/sbin/init"]
